// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYEwJrmADmQHfZng3DFNvRVteTMexMFlE',
    appId: '1:889874357820:web:2ac547d9707aee5fd6ad39',
    messagingSenderId: '889874357820',
    projectId: 'chatapp-fc859',
    authDomain: 'chatapp-fc859.firebaseapp.com',
    storageBucket: 'chatapp-fc859.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1f5wgI2Ev-Ch4NCnPNB0Yw2BgaqNm0uk',
    appId: '1:889874357820:android:2c26ee599efde417d6ad39',
    messagingSenderId: '889874357820',
    projectId: 'chatapp-fc859',
    storageBucket: 'chatapp-fc859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvab7E2NzYyhH2mI3GhE_CP0RHnW_32is',
    appId: '1:889874357820:ios:5b403f3ace01d66dd6ad39',
    messagingSenderId: '889874357820',
    projectId: 'chatapp-fc859',
    storageBucket: 'chatapp-fc859.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvab7E2NzYyhH2mI3GhE_CP0RHnW_32is',
    appId: '1:889874357820:ios:5b403f3ace01d66dd6ad39',
    messagingSenderId: '889874357820',
    projectId: 'chatapp-fc859',
    storageBucket: 'chatapp-fc859.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
